services:
  unchef:
    image: ghcr.io/rfalias/unchef:latest
    network_mode: bridge
    volumes:
      - /data/unchef:/data
    environment:
      DATABASE_URL: sqlite+aiosqlite:////data/food_app.db
      JWT_SECRET: changeme
      JWT_LIFETIME_SECONDS: 2592000
      CORS_ORIGINS: https://chef.example.com
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.unchef-whitelist.ipwhitelist.sourcerange=127.0.0.1/32,192.168.0.0/16,172.0.0.0/8
      - traefik.http.routers.unchef.rule=Host(`chef.example.com`)
      - traefik.http.routers.unchef.entrypoints=websecure
      - traefik.http.routers.unchef.tls.certresolver=mydnschallenge
      - traefik.http.routers.unchef.middlewares=unchef-whitelist
      - traefik.http.services.unchef.loadbalancer.server.port=80
      - traefik.http.routers.unchef.service=unchef
